### ISSUE TITLE
What is perplexity API KEY？

### ISSUE THREAD

**Issue by dashfahojg** [chtmp223/topicGPT#10]
Is it just as the same as normal API KEY used in chatgpt API？

**Comment by chtmp223** [comment]
The Perplexity API is a separate API entirely, designed to support open-source models as outlined in its documentation: https://docs.perplexity.ai/home. With our latest release (v0.2.0) of the topicgpt_python package (https://pypi.org/project/topicgpt-python/), we have removed support for the Perplexity API. Instead, we now provide support for vLLM inference for those interested in using open-source models.
