### ISSUE TITLE
Using Gemini API, instead of Vertex AI API

### ISSUE THREAD

**Issue by tlyim** [chtmp223/topicGPT#11]
Instead of Vertex AI API, is there a chance that Gemini API can also be supported?

https://ai.google.dev/pricing#1_5flash

Thanks for your consideration.

**Comment by tlyim** [comment]
In case this is a relevant reference: 

https://cloud.google.com/vertex-ai/generative-ai/docs/migrate/migrate-google-ai

**Comment by chtmp223** [comment]
I will look into this (+ Azure API) next week and let you know!

**Comment by chtmp223** [comment]
Hello, I added support for Gemini API in v0.2.4 of the package. Feel free to re-open this issue again if you have trouble running it.

**Comment by tlyim** [comment]
That's great news!
Thank you so much for the prompt response.
