### ISSUE TITLE
Required code of harmonic mean of Purity and Inverse Purity

### ISSUE THREAD

**Issue by forthewebsites1** [chtmp223/topicGPT#2]
Hi,

I was going through your paper TopicGPT and came across the matrix through which you've done evaluation -

harmonic mean of Purity and Inverse Purity -
(equation/formula attached)

Can you pls provide it's code?
(I can't find in in your repo)

<img width="312" alt="Screenshot 2023-12-15 at 1 40 17 PM" src="https://github.com/chtmp223/topicGPT/assets/146323303/d3b3fcb5-226b-43b5-a6f4-845e20a1f294">

**Comment by chtmp223** [comment]
Hello!

I added a commit to do this: [a42a7f0](https://github.com/chtmp223/topicGPT/commit/a42a7f0fc84a9325bfbb6ac2155dc8ac51f1b0db). You can find the code to calculate the harmonic purity between two sets of clusterings at the bottom of the `utils.py` file.
