### ISSUE TITLE
topicGPT or TopicGPT ?

### ISSUE THREAD

**Issue by JeffreyLau521** [chtmp223/topicGPT#4]
Will the author consider wrapping this package so that everyone can use it more conveniently?
In addition, there is a package named "**TopicGPT**", is it related to the author's "**topicGPT**"?
https://github.com/LMU-Seminar-LLMs/TopicGPT

**Comment by chtmp223** [comment]
We will consider developing a package in the future! And no, the other package is not related to our project.
